export const ADD_TO_CART= 'ADD_TO_CART';
export const ADD_TO_CART_FAIL= 'ADD_TO_CART_FAIL';
export const SET_TOTAL_CART_FAIL= 'SET_TOTAL_CART_FAIL';
export const SET_TOTAL_CART= 'SET_TOTAL_CART';
export const UPDATE_CART_ITEM= 'UPDATE_CART_ITEM';
export const UPDATE_CART_ITEM_FAIL= 'UPDATE_CART_ITEM_FAIL';

export const REMOVE_ITEM_FAIL= 'REMOVE_ITEM_FAIL';

export const REMOVE_ITEM= 'REMOVE_ITEM';
export const SUB_QUANTITY= 'SUB_QUANTITY';
export const ADD_QUANTITY= ' ADD_QUANTITY';
export const ADD_SHIPPING= 'ADD_SHIPPING';
export const GET_DEPARTMENT= 'GET_DEPARTMENT';
export const GET_DEPARTMENT_FAIL= 'GET_DEPARTMENT_FAIL';